spring:
  application:
    name: my_project
  profiles: test

redis:
  common:
    timeout: 5000
    connection: 54.159.208.93
    pool:
      maxTotal: 1024
      maxIdle: 200
      minIdle: 20
      maxWaitMillis: 1000
      testOnBorrow: true

server:
  port: 9000

logging:
  level: info

#elasticsearch:
#  clusterName: test
#  nodes:
#    - 127.0.0.1:9300

#hbase:
#  quorum: 127.0.0.1
#  port: 2181