spring:
  profiles: test

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 5000

server:
  port: 9000

message: hahahha

elasticsearch:
  clusterName: test
  nodes:
    - 127.0.0.1:9300

hbase:
  quorum: 127.0.0.1
  port: 2181