spring:
  application:
    name: my_project
  profiles: test


redis:
  host: 127.0.0.1
  port: 6379
  timeout: 5000

server:
  port: 9000

logging:
  level: info


#redisCondition: true

#elasticsearch:
#  clusterName: test
#  nodes:
#    - 127.0.0.1:9300

#hbase:
#  quorum: 127.0.0.1
#  port: 2181